/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g4s21halpp2;

import javax.swing.JOptionPane;

/**
 *
 * @author panch
 */
public class Frmuno extends javax.swing.JFrame {

    /**
     * Creates new form Frmuno
     */
    public Frmuno() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d_p_contenedor = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        mi_suma = new javax.swing.JMenu();
        mi_sumaa = new javax.swing.JMenuItem();
        mi_resta = new javax.swing.JMenuItem();
        mi_multiplicacion = new javax.swing.JMenuItem();
        mi_division = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout d_p_contenedorLayout = new javax.swing.GroupLayout(d_p_contenedor);
        d_p_contenedor.setLayout(d_p_contenedorLayout);
        d_p_contenedorLayout.setHorizontalGroup(
            d_p_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        d_p_contenedorLayout.setVerticalGroup(
            d_p_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        mi_suma.setText("Operacion");

        mi_sumaa.setText("Suma");
        mi_sumaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_sumaaActionPerformed(evt);
            }
        });
        mi_suma.add(mi_sumaa);

        mi_resta.setText("Resta");
        mi_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_restaActionPerformed(evt);
            }
        });
        mi_suma.add(mi_resta);

        mi_multiplicacion.setText("Multiplicación");
        mi_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_multiplicacionActionPerformed(evt);
            }
        });
        mi_suma.add(mi_multiplicacion);

        mi_division.setText("División");
        mi_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_divisionActionPerformed(evt);
            }
        });
        mi_suma.add(mi_division);

        jMenuBar1.add(mi_suma);

        exit.setText("Salir");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(d_p_contenedor)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(d_p_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_divisionActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Se presiono botón división");
        
        JIF_division objdivision = new JIF_division();
        objdivision.setVisible(true);
        setLocationRelativeTo(null);
        d_p_contenedor.add(objdivision);
    }//GEN-LAST:event_mi_divisionActionPerformed

    private void mi_sumaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_sumaaActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Se presiono botón Suma");
        
        JIF_suma objsuma = new JIF_suma();
        setLocationRelativeTo(null); 
        objsuma.setVisible(true);       
        d_p_contenedor.add(objsuma);
        
        
    }//GEN-LAST:event_mi_sumaaActionPerformed

    private void mi_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_multiplicacionActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Se presiono botón multiplicacion");
        
        JIF_multiplicacion objmultiplicacion = new JIF_multiplicacion();
        objmultiplicacion.setVisible(true);
        setLocationRelativeTo(null);
        d_p_contenedor.add(objmultiplicacion);
        
    }//GEN-LAST:event_mi_multiplicacionActionPerformed

    private void mi_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_restaActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Se presiono botón resta");
        
        JIF_resta objresta = new JIF_resta();
        objresta.setVisible(true);
        setLocationRelativeTo(null);
        d_p_contenedor.add(objresta);
    }//GEN-LAST:event_mi_restaActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked
    
 
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmuno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Frmuno().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane d_p_contenedor;
    private javax.swing.JMenu exit;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mi_division;
    private javax.swing.JMenuItem mi_multiplicacion;
    private javax.swing.JMenuItem mi_resta;
    private javax.swing.JMenu mi_suma;
    private javax.swing.JMenuItem mi_sumaa;
    // End of variables declaration//GEN-END:variables
}
